spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@gmail.com   #your <Login User to SMTP server>
    password: password@123a   #your <Login password to SMTP server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    debug: true
  cache:
    type: simple
