spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bareetsingh0001@gmail.com
    password: jqzrqgrinkgptmhl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    debug: true
  cache:
    type: simple
